name: Bundle CI
on:
  push:
    branches: ['master']

jobs:

  tests:
    name: "Tests ${{ matrix.php-version }} ${{ matrix.dependency-versions }} deps ${{ matrix.dependency-versions }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # normal, highest, non-dev installs
        php-version: ['8.0', '8.1']
        composer-options: ['--prefer-stable']
        dependency-versions: ['highest']
        include:
          # testing lowest php with lowest dependencies
          - php-version: '8.0'
            dependency-versions: 'lowest'
            composer-options: '--prefer-lowest'
          # testing dev versions with highest PHP
          - php-version: '8.1'
            dependency-versions: 'highest'
            composer-options: '' # allow dev deps

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
            coverage: "none"
            php-version: "${{ matrix.php-version }}"

      - name: "Composer install"
        uses: "ramsey/composer-install@v2"
        with:
            dependency-versions: "${{ matrix.dependency-versions }}"
            composer-options: "--prefer-dist --no-progress"

      - name: Run PHPUnit tests
        run: "./vendor/bin/phpunit"
